name: main

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
          architecture: 'x64'
      - name: Install dependencies
        run: bundle install
      - name: Run Ruby
        run: bundle exec ruby main.rb
        env: 
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          API_KEY: ${{secrets.API_KEY}}
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
